# This is a basic workflow to help you get started with Actions

name: Maven Package and Upload

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ java ]
  pull_request:
    branches: [ java ]
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: Apt Update
          run: |
            sudo apt-get update > /dev/null
            sudo ln -fs /usr/share/zoneinfo/Asia/Tokyo /etc/localtime 
            sudo apt-get install tzdata -y > /dev/null
            sudo dpkg-reconfigure --frontend noninteractive tzdata > /dev/null
            sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y > /dev/null
        - name: Install Docker
          run: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /dev/null
            sudo apt-get update > /dev/null && sudo apt-get install docker-ce > /dev/null
            sudo usermod -aG docker $USER
        - name: Docker Build
          run: |
            docker build --force-rm --tag dockerfile:build . 
        - name: Docker Run
          run: |
            docker run -i -v $(pwd):/data dockerfile:build
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: true
            title: "Development Build"
            files: |
              LICENSE*
              target/*.jar
        - uses: actions/upload-artifact@v2
          with:
            name: package (JAR Files)
            path: |
              target/*.jar
